In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import warnings

warnings.filterwarnings("ignore", category=UserWarning)

# sys.path.insert(0, "/Users/poorna/Downloads/CE-updated/calibrated_explanations/src")

# Import the necessary libraries
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from calibrated_explanations import WrapCalibratedExplainer, __version__

print(f"calibrated_explanations {__version__}")

calibrated_explanations 1.0.0rc1

In [3]:
# Load and preprocess the data
num_to_test = 10  # number of instances to test, one from each class
dataset = "diabetes_full"
delimiter = ","
model = "RF"

filename = "../../tests/data/diabetes_full.csv"
df = pd.read_csv(filename, delimiter=delimiter)
target = "Y"
X, y = df.drop(target, axis=1), df[target]
no_of_classes = len(np.unique(y))
no_of_features = X.shape[1]
no_of_instances = X.shape[0]

# find categorical features
categorical_features = [i for i in range(no_of_features) if len(np.unique(X.iloc[:, i])) < 10]

# select test instances from each class and split into train, cal and test
idx = np.argsort(y.values).astype(int)
X, y = X.values[idx, :], y.values[idx]
test_index = np.array(
    [
        *range(int(num_to_test / 2)),
        *range(no_of_instances - 1, no_of_instances - int(num_to_test / 2) - 1, -1),
    ]
)
train_index = np.setdiff1d(np.array(range(no_of_instances)), test_index)
x_train, x_test = X[train_index, :], X[test_index, :]
y_train, y_test = y[train_index], y[test_index]
X_prop_train, x_cal, y_prop_train, y_cal = train_test_split(
    x_train, y_train, test_size=0.33, random_state=42, stratify=y_train
)

In [4]:
# Train the model and create the explainer
model = RandomForestClassifier()

model.fit(X_prop_train, y_prop_train)

ce = WrapCalibratedExplainer(model)
ce.calibrate(x_cal, y_cal, feature_names=df.columns, categorical_features=categorical_features, class_labels={0: "Non-diabetic", 1: "Diabetic"})

WrapCalibratedExplainer(learner=RandomForestClassifier(), fitted=True, calibrated=True,
		explainer=CalibratedExplainer(mode=classification, learner=RandomForestClassifier()))

In [5]:
factual_explanations = ce.explain_factual(x_test)
print("Probability [lower and upper bound] for Diabetic:")
print(
    *zip(
        [
            f"Instance {i}: {exp.prediction['predict']:.3f} [{exp.prediction['low']:5.3f}, {exp.prediction['high']:5.3f}]"
            for i, exp in enumerate(factual_explanations)
        ], strict=False
    ),
    sep="\n",
)

Probability [lower and upper bound] for Diabetic:
('Instance 0: 0.429 [0.412, 0.441]',)
('Instance 1: 0.499 [0.490, 0.508]',)
('Instance 2: 0.499 [0.490, 0.508]',)
('Instance 3: 0.062 [0.034, 0.064]',)
('Instance 4: 0.518 [0.492, 0.545]',)
('Instance 5: 0.407 [0.375, 0.429]',)
('Instance 6: 0.429 [0.412, 0.441]',)
('Instance 7: 0.571 [0.500, 0.667]',)
('Instance 8: 0.693 [0.680, 0.722]',)
('Instance 9: 0.276 [0.235, 0.292]',)

Example demonstrating the new to_narrative API.

This shows the clean API for generating narratives from calibrated explanations.

In [6]:
# The new to_narrative method provides a clean API:
explanations = factual_explanations

# Basic usage
narratives = explanations[0].to_narrative(
    expertise_level=("beginner", "advanced"),
    output_format="text",
)
print(narratives)

================================================================================
Instance 0
================================================================================

Factual Explanation (Advanced):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429
Prediction Interval: [0.412, 0.441]

Factors impacting the calibrated probability for class Diabetic positively:
Pregnancies (13.0) > 6.50               - weight ~ 0.267 [0.262, 0.295]
Glucose (145.0) > 122.50                - weight ~ 0.152 [0.137, 0.193]
DiabetesPedigreeFunction (0.24) <= 0.53 - weight ~ 0.007 [-0.008, 0.029] [[!] direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (22.2) <= 28.65                     - weight ~ -0.071 [-0.080, -0.061]

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Pregnancies (13.0) > 6.50
* Glucose (145.0) > 122.50
* DiabetesPedigreeFunction (0.24) <= 0.53 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* BMI (22.2) <= 28.65

In [7]:
# Different output formats:

# 1. DataFrame (default) - returns pandas DataFrame
df_narratives = explanations.to_narrative(
    expertise_level=("beginner", "advanced"), output_format="markdown"
)
print(df_narratives)

## Instance 0

### Factual Explanation (Advanced)

```
Prediction: Non-diabetic
Calibrated Probability: 0.429
Prediction Interval: [0.412, 0.441]

Factors impacting the calibrated probability for class Diabetic positively:
Pregnancies (13.0) > 6.50               - weight ~ 0.267 [0.262, 0.295]
Glucose (145.0) > 122.50                - weight ~ 0.152 [0.137, 0.193]
DiabetesPedigreeFunction (0.24) <= 0.53 - weight ~ 0.007 [-0.008, 0.029] [[!] direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (22.2) <= 28.65                     - weight ~ -0.071 [-0.080, -0.061]
```

### Factual Explanation (Beginner)

```
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Pregnancies (13.0) > 6.50
* Glucose (145.0) > 122.50
* DiabetesPedigreeFunction (0.24) <= 0.53 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* BMI (22.2) <= 28.65
```

## Instance 1

### Factual Explanation (Advanced)

```
Prediction: Non-diabetic
Calibrated Probability: 0.499
Prediction Interval: [0.490, 0.508]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (34.1) > 28.65           - weight ~ 0.260 [0.250, 0.300]
Age (38.0) > 28.50           - weight ~ 0.112 [0.080, 0.166]
SkinThickness (0.0) <= 32.50 - weight ~ 0.071 [0.058, 0.087]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (117.0) <= 122.50    - weight ~ -0.179 [-0.222, -0.158]
BloodPressure (92.0) > 71.00 - weight ~ -0.006 [-0.022, 0.009] [[!] direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 28.65
* Age (38.0) > 28.50
* SkinThickness (0.0) <= 32.50

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* BloodPressure (92.0) > 71.00 [[!] direction uncertain]
```

## Instance 2

### Factual Explanation (Advanced)

```
Prediction: Non-diabetic
Calibrated Probability: 0.499
Prediction Interval: [0.490, 0.508]

Factors impacting the calibrated probability for class Diabetic positively:
Age (60.0) > 28.50                     - weight ~ 0.338 [0.332, 0.366]
BMI (36.0) > 28.65                     - weight ~ 0.294 [0.282, 0.339]
DiabetesPedigreeFunction (0.55) > 0.53 - weight ~ 0.078 [0.062, 0.100]
BloodPressure (75.0) > 71.00           - weight ~ 0.071 [0.058, 0.087]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (109.0) <= 122.50              - weight ~ -0.188 [-0.223, -0.172]
```

### Factual Explanation (Beginner)

```
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* Age (60.0) > 28.50
* BMI (36.0) > 28.65
* DiabetesPedigreeFunction (0.55) > 0.53
* BloodPressure (75.0) > 71.00

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50
```

## Instance 3

### Factual Explanation (Advanced)

```
Prediction: Non-diabetic
Calibrated Probability: 0.062
Prediction Interval: [0.034, 0.064]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (108.0) <= 122.50               - weight ~ -0.282 [-0.311, -0.225]
Age (25.0) <= 28.50                     - weight ~ -0.219 [-0.234, -0.186]
Pregnancies (3.0) <= 6.50               - weight ~ -0.155 [-0.168, -0.112]
SkinThickness (24.0) <= 32.50           - weight ~ -0.027 [-0.031, 0.015] [[!] direction uncertain]
DiabetesPedigreeFunction (0.22) <= 0.53 - weight ~ -0.025 [-0.030, 0.021] [[!] direction uncertain]
BMI (26.0) <= 28.65                     - weight ~ -0.024 [-0.028, 0.021] [[!] direction uncertain]
BloodPressure (62.0) <= 71.00           - weight ~ -0.024 [-0.028, 0.021] [[!] direction uncertain]
Insulin (0.0) <= 189.00                 - weight ~ -0.003 [-0.005, 0.028] [[!] direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
```

### Factual Explanation (Beginner)

```
Prediction: Non-diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* Glucose (108.0) <= 122.50
* Age (25.0) <= 28.50
* Pregnancies (3.0) <= 6.50
* SkinThickness (24.0) <= 32.50 [[!] direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.53 [[!] direction uncertain]
* BMI (26.0) <= 28.65 [[!] direction uncertain]
* BloodPressure (62.0) <= 71.00 [[!] direction uncertain]
* Insulin (0.0) <= 189.00 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
```

## Instance 4

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.518
Prediction Interval: [0.492, 0.545]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (32.0) > 28.65                      - weight ~ 0.065 [0.054, 0.080]
Glucose (137.0) > 122.50                - weight ~ 0.042 [0.032, 0.054]
Age (39.0) > 28.50                      - weight ~ 0.018 [0.009, 0.028]
Pregnancies (7.0) > 6.50                - weight ~ 0.018 [0.009, 0.028]

Factors impacting the calibrated probability for class Diabetic negatively:
DiabetesPedigreeFunction (0.39) <= 0.53 - weight ~ -0.173 [-0.205, -0.158]
Insulin (0.0) <= 189.00                 - weight ~ -0.111 [-0.185, -0.066]
BloodPressure (90.0) > 71.00            - weight ~ -0.101 [-0.185, -0.048]
SkinThickness (41.0) > 32.50            - weight ~ -0.091 [-0.168, -0.038]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.518

Factors impacting the probability for class Diabetic positively:
* BMI (32.0) > 28.65
* Glucose (137.0) > 122.50
* Age (39.0) > 28.50
* Pregnancies (7.0) > 6.50

Factors impacting the probability for class Diabetic negatively:
* DiabetesPedigreeFunction (0.39) <= 0.53
* Insulin (0.0) <= 189.00
* BloodPressure (90.0) > 71.00
* SkinThickness (41.0) > 32.50
```

## Instance 5

### Factual Explanation (Advanced)

```
Prediction: Non-diabetic
Calibrated Probability: 0.407
Prediction Interval: [0.375, 0.429]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (30.0) > 28.65                      - weight ~ 0.183 [0.162, 0.235]
Pregnancies (7.0) > 6.50                - weight ~ 0.131 [0.115, 0.171]
Age (32.0) > 28.50                      - weight ~ 0.059 [0.007, 0.157]
SkinThickness (0.0) <= 32.50            - weight ~ 0.020 [-0.012, 0.073] [[!] direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (100.0) <= 122.50               - weight ~ -0.222 [-0.295, -0.177]
Insulin (0.0) <= 189.00                 - weight ~ -0.092 [-0.102, -0.083]
BloodPressure (0.0) <= 71.00            - weight ~ -0.015 [-0.030, 0.007] [[!] direction uncertain]
DiabetesPedigreeFunction (0.48) <= 0.53 - weight ~ -0.007 [-0.026, 0.020] [[!] direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Non-diabetic
Calibrated Probability: 0.407

Factors impacting the probability for class Diabetic positively:
* BMI (30.0) > 28.65
* Pregnancies (7.0) > 6.50
* Age (32.0) > 28.50
* SkinThickness (0.0) <= 32.50 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 122.50
* Insulin (0.0) <= 189.00
* BloodPressure (0.0) <= 71.00 [[!] direction uncertain]
* DiabetesPedigreeFunction (0.48) <= 0.53 [[!] direction uncertain]
```

## Instance 6

### Factual Explanation (Advanced)

```
Prediction: Non-diabetic
Calibrated Probability: 0.429
Prediction Interval: [0.412, 0.441]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (166.0) > 122.50               - weight ~ 0.191 [0.179, 0.227]
Age (51.0) > 28.50                     - weight ~ 0.034 [0.005, 0.083]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (25.8) <= 28.65                    - weight ~ -0.183 [-0.257, -0.131]
Pregnancies (5.0) <= 6.50              - weight ~ -0.083 [-0.105, -0.062]
Insulin (175.0) <= 189.00              - weight ~ -0.071 [-0.080, -0.061]
SkinThickness (19.0) <= 32.50          - weight ~ -0.071 [-0.080, -0.061]
DiabetesPedigreeFunction (0.59) > 0.53 - weight ~ -0.024 [-0.035, -0.009]
```

### Factual Explanation (Beginner)

```
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 122.50
* Age (51.0) > 28.50

Factors impacting the probability for class Diabetic negatively:
* BMI (25.8) <= 28.65
* Pregnancies (5.0) <= 6.50
* Insulin (175.0) <= 189.00
* SkinThickness (19.0) <= 32.50
* DiabetesPedigreeFunction (0.59) > 0.53
```

## Instance 7

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.571
Prediction Interval: [0.500, 0.667]

Factors impacting the calibrated probability for class Diabetic positively:
Age (59.0) > 28.50                     - weight ~ 0.143 [0.130, 0.160]
Glucose (189.0) > 122.50               - weight ~ 0.119 [0.108, 0.134]
BMI (30.1) > 28.65                     - weight ~ 0.096 [0.085, 0.108]
Insulin (846.0) > 189.00               - weight ~ 0.072 [0.063, 0.082]

Factors impacting the calibrated probability for class Diabetic negatively:
Pregnancies (1.0) <= 6.50              - weight ~ -0.122 [-0.151, -0.109]
BloodPressure (60.0) <= 71.00          - weight ~ -0.086 [-0.149, -0.054]
SkinThickness (23.0) <= 32.50          - weight ~ -0.086 [-0.149, -0.054]
DiabetesPedigreeFunction (0.4) <= 0.53 - weight ~ -0.038 [-0.114, 0.016] [[!] direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.571

Factors impacting the probability for class Diabetic positively:
* Age (59.0) > 28.50
* Glucose (189.0) > 122.50
* BMI (30.1) > 28.65
* Insulin (846.0) > 189.00

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (1.0) <= 6.50
* BloodPressure (60.0) <= 71.00
* SkinThickness (23.0) <= 32.50
* DiabetesPedigreeFunction (0.4) <= 0.53 [[!] direction uncertain]
```

## Instance 8

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.693
Prediction Interval: [0.680, 0.722]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (168.0) > 122.50               - weight ~ 0.217 [0.207, 0.229]
DiabetesPedigreeFunction (0.54) > 0.53 - weight ~ 0.105 [0.061, 0.136]
BMI (38.0) > 28.65                     - weight ~ 0.034 [-0.028, 0.067] [[!] direction uncertain]
BloodPressure (74.0) > 71.00           - weight ~ 0.006 [-0.029, 0.022] [[!] direction uncertain]
Age (34.0) > 28.50                     - weight ~ 0.000 [-0.029, 0.013] [[!] direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Pregnancies (10.0) > 6.50              - weight ~ -0.090 [-0.259, -0.045]
Insulin (0.0) <= 189.00                - weight ~ -0.057 [-0.164, -0.021]
SkinThickness (0.0) <= 32.50           - weight ~ -0.012 [-0.074, 0.013] [[!] direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.693

Factors impacting the probability for class Diabetic positively:
* Glucose (168.0) > 122.50
* DiabetesPedigreeFunction (0.54) > 0.53
* BMI (38.0) > 28.65 [[!] direction uncertain]
* BloodPressure (74.0) > 71.00 [[!] direction uncertain]
* Age (34.0) > 28.50 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (10.0) > 6.50
* Insulin (0.0) <= 189.00
* SkinThickness (0.0) <= 32.50 [[!] direction uncertain]
```

## Instance 9

### Factual Explanation (Advanced)

```
Prediction: Non-diabetic
Calibrated Probability: 0.276
Prediction Interval: [0.235, 0.292]

Factors impacting the calibrated probability for class Diabetic positively:
Pregnancies (8.0) > 6.50     - weight ~ 0.115 [0.109, 0.143]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (0.0) <= 28.65           - weight ~ -0.223 [-0.232, -0.214]
Insulin (0.0) <= 189.00      - weight ~ -0.152 [-0.165, -0.136]
Age (54.0) > 28.50           - weight ~ -0.138 [-0.157, -0.111]
BloodPressure (96.0) > 71.00 - weight ~ -0.131 [-0.152, -0.099]
```

### Factual Explanation (Beginner)

```
Prediction: Non-diabetic
Calibrated Probability: 0.276

Factors impacting the probability for class Diabetic positively:
* Pregnancies (8.0) > 6.50

Factors impacting the probability for class Diabetic negatively:
* BMI (0.0) <= 28.65
* Insulin (0.0) <= 189.00
* Age (54.0) > 28.50
* BloodPressure (96.0) > 71.00
```

In [8]:
# 2. Text - returns formatted text string
text_narratives = explanations.to_narrative(
    expertise_level="beginner", output_format="text"
)
print(text_narratives)
text_narratives = explanations.add_conjunctions(max_rule_size=3).to_narrative(
    expertise_level="beginner", output_format="text"
)
print(text_narratives)

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Pregnancies (13.0) > 6.50
* Glucose (145.0) > 122.50
* DiabetesPedigreeFunction (0.24) <= 0.53 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* BMI (22.2) <= 28.65

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 28.65
* Age (38.0) > 28.50
* SkinThickness (0.0) <= 32.50

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* BloodPressure (92.0) > 71.00 [[!] direction uncertain]

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* Age (60.0) > 28.50
* BMI (36.0) > 28.65
* DiabetesPedigreeFunction (0.55) > 0.53
* BloodPressure (75.0) > 71.00

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* Glucose (108.0) <= 122.50
* Age (25.0) <= 28.50
* Pregnancies (3.0) <= 6.50
* SkinThickness (24.0) <= 32.50 [[!] direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.53 [[!] direction uncertain]
* BMI (26.0) <= 28.65 [[!] direction uncertain]
* BloodPressure (62.0) <= 71.00 [[!] direction uncertain]
* Insulin (0.0) <= 189.00 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.518

Factors impacting the probability for class Diabetic positively:
* BMI (32.0) > 28.65
* Glucose (137.0) > 122.50
* Age (39.0) > 28.50
* Pregnancies (7.0) > 6.50

Factors impacting the probability for class Diabetic negatively:
* DiabetesPedigreeFunction (0.39) <= 0.53
* Insulin (0.0) <= 189.00
* BloodPressure (90.0) > 71.00
* SkinThickness (41.0) > 32.50

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.407

Factors impacting the probability for class Diabetic positively:
* BMI (30.0) > 28.65
* Pregnancies (7.0) > 6.50
* Age (32.0) > 28.50
* SkinThickness (0.0) <= 32.50 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 122.50
* Insulin (0.0) <= 189.00
* BloodPressure (0.0) <= 71.00 [[!] direction uncertain]
* DiabetesPedigreeFunction (0.48) <= 0.53 [[!] direction uncertain]

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 122.50
* Age (51.0) > 28.50

Factors impacting the probability for class Diabetic negatively:
* BMI (25.8) <= 28.65
* Pregnancies (5.0) <= 6.50
* Insulin (175.0) <= 189.00
* SkinThickness (19.0) <= 32.50
* DiabetesPedigreeFunction (0.59) > 0.53

================================================================================
Instance 7
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.571

Factors impacting the probability for class Diabetic positively:
* Age (59.0) > 28.50
* Glucose (189.0) > 122.50
* BMI (30.1) > 28.65
* Insulin (846.0) > 189.00

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (1.0) <= 6.50
* BloodPressure (60.0) <= 71.00
* SkinThickness (23.0) <= 32.50
* DiabetesPedigreeFunction (0.4) <= 0.53 [[!] direction uncertain]

================================================================================
Instance 8
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.693

Factors impacting the probability for class Diabetic positively:
* Glucose (168.0) > 122.50
* DiabetesPedigreeFunction (0.54) > 0.53
* BMI (38.0) > 28.65 [[!] direction uncertain]
* BloodPressure (74.0) > 71.00 [[!] direction uncertain]
* Age (34.0) > 28.50 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (10.0) > 6.50
* Insulin (0.0) <= 189.00
* SkinThickness (0.0) <= 32.50 [[!] direction uncertain]

================================================================================
Instance 9
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.276

Factors impacting the probability for class Diabetic positively:
* Pregnancies (8.0) > 6.50

Factors impacting the probability for class Diabetic negatively:
* BMI (0.0) <= 28.65
* Insulin (0.0) <= 189.00
* Age (54.0) > 28.50
* BloodPressure (96.0) > 71.00

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Pregnancies (13.0) > 6.50
* Glucose (145.0) > 122.50
* (BMI (22.2) <= 28.65 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* DiabetesPedigreeFunction (0.24) <= 0.53 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (BMI (22.2) <= 28.65 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (BMI (22.2) <= 28.65 AND Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Glucose (145.0) > 122.50 AND BMI (22.2) <= 28.65)
* (BMI (22.2) <= 28.65 AND Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Pregnancies (13.0) > 6.50 AND BMI (22.2) <= 28.65)
* BMI (22.2) <= 28.65

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 28.65
* (BMI (34.1) > 28.65 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* (Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)
* (Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* (Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 71.00)
* (BloodPressure (92.0) > 71.00 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)
* (BloodPressure (92.0) > 71.00 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* Age (38.0) > 28.50
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)
* (Glucose (117.0) <= 122.50 AND SkinThickness (0.0) <= 32.50)
* SkinThickness (0.0) <= 32.50
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 71.00)

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* (SkinThickness (0.0) <= 32.50 AND BMI (34.1) > 28.65)
* (BloodPressure (92.0) > 71.00 AND SkinThickness (0.0) <= 32.50)
* (SkinThickness (0.0) <= 32.50 AND Age (38.0) > 28.50)
* (BMI (34.1) > 28.65 AND Age (38.0) > 28.50) [[!] direction uncertain]
* (BloodPressure (92.0) > 71.00 AND Age (38.0) > 28.50) [[!] direction uncertain]
* BloodPressure (92.0) > 71.00 [[!] direction uncertain]
* (BloodPressure (92.0) > 71.00 AND BMI (34.1) > 28.65) [[!] direction uncertain]

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* Age (60.0) > 28.50
* BMI (36.0) > 28.65
* (Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (BloodPressure (75.0) > 71.00 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (BMI (36.0) > 28.65 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)
* (BMI (36.0) > 28.65 AND Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)
* (Glucose (109.0) <= 122.50 AND BMI (36.0) > 28.65)
* DiabetesPedigreeFunction (0.55) > 0.53
* BloodPressure (75.0) > 71.00
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (Glucose (109.0) <= 122.50 AND DiabetesPedigreeFunction (0.55) > 0.53)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50
* (BloodPressure (75.0) > 71.00 AND DiabetesPedigreeFunction (0.55) > 0.53)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Age (60.0) > 28.50)
* (BMI (36.0) > 28.65 AND DiabetesPedigreeFunction (0.55) > 0.53)
* (BloodPressure (75.0) > 71.00 AND Age (60.0) > 28.50)
* (BMI (36.0) > 28.65 AND Age (60.0) > 28.50)
* (BloodPressure (75.0) > 71.00 AND BMI (36.0) > 28.65)

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (SkinThickness (24.0) <= 32.50 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (BloodPressure (62.0) <= 71.00 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (SkinThickness (24.0) <= 32.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (BloodPressure (62.0) <= 71.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (SkinThickness (24.0) <= 32.50 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (Pregnancies (3.0) <= 6.50 AND Age (25.0) <= 28.50)
* (Glucose (108.0) <= 122.50 AND DiabetesPedigreeFunction (0.22) <= 0.53)
* (SkinThickness (24.0) <= 32.50 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 28.65 AND Age (25.0) <= 28.50)
* (SkinThickness (24.0) <= 32.50 AND Age (25.0) <= 28.50)
* (BloodPressure (62.0) <= 71.00 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Age (25.0) <= 28.50)
* (Pregnancies (3.0) <= 6.50 AND DiabetesPedigreeFunction (0.22) <= 0.53)
* (BloodPressure (62.0) <= 71.00 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 28.65 AND Pregnancies (3.0) <= 6.50)
* (BloodPressure (62.0) <= 71.00 AND Age (25.0) <= 28.50)
* (BloodPressure (62.0) <= 71.00 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Age (25.0) <= 28.50)
* (Pregnancies (3.0) <= 6.50 AND SkinThickness (24.0) <= 32.50)
* (BloodPressure (62.0) <= 71.00 AND Pregnancies (3.0) <= 6.50)
* (Insulin (0.0) <= 189.00 AND Pregnancies (3.0) <= 6.50)
* (BloodPressure (62.0) <= 71.00 AND SkinThickness (24.0) <= 32.50) [[!] direction uncertain]
* (BMI (26.0) <= 28.65 AND SkinThickness (24.0) <= 32.50) [[!] direction uncertain]
* (BloodPressure (62.0) <= 71.00 AND DiabetesPedigreeFunction (0.22) <= 0.53) [[!] direction uncertain]
* (BMI (26.0) <= 28.65 AND DiabetesPedigreeFunction (0.22) <= 0.53) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (108.0) <= 122.50
* Age (25.0) <= 28.50
* Pregnancies (3.0) <= 6.50
* SkinThickness (24.0) <= 32.50 [[!] direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.53 [[!] direction uncertain]
* BMI (26.0) <= 28.65 [[!] direction uncertain]
* BloodPressure (62.0) <= 71.00 [[!] direction uncertain]
* Insulin (0.0) <= 189.00 [[!] direction uncertain]

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.518

Factors impacting the probability for class Diabetic positively:
* (BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (BloodPressure (90.0) > 71.00 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (BMI (32.0) > 28.65 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (Pregnancies (7.0) > 6.50 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (Insulin (0.0) <= 189.00 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (Insulin (0.0) <= 189.00 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (BloodPressure (90.0) > 71.00 AND BMI (32.0) > 28.65)
* (Pregnancies (7.0) > 6.50 AND SkinThickness (41.0) > 32.50)
* (Insulin (0.0) <= 189.00 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* BMI (32.0) > 28.65
* (Pregnancies (7.0) > 6.50 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (Pregnancies (7.0) > 6.50 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (SkinThickness (41.0) > 32.50 AND Insulin (0.0) <= 189.00)
* (Age (39.0) > 28.50 AND BloodPressure (90.0) > 71.00)
* (BloodPressure (90.0) > 71.00 AND Insulin (0.0) <= 189.00)
* Glucose (137.0) > 122.50
* (DiabetesPedigreeFunction (0.39) <= 0.53 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (Insulin (0.0) <= 189.00 AND BMI (32.0) > 28.65) [[!] direction uncertain]
* Age (39.0) > 28.50
* Pregnancies (7.0) > 6.50
* (Age (39.0) > 28.50 AND BMI (32.0) > 28.65) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.39) <= 0.53 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.39) <= 0.53 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50) [[!] direction uncertain]
* (SkinThickness (41.0) > 32.50 AND DiabetesPedigreeFunction (0.39) <= 0.53) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* DiabetesPedigreeFunction (0.39) <= 0.53
* (Pregnancies (7.0) > 6.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Insulin (0.0) <= 189.00 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BloodPressure (90.0) > 71.00 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BMI (32.0) > 28.65 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Age (39.0) > 28.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* Insulin (0.0) <= 189.00
* BloodPressure (90.0) > 71.00
* SkinThickness (41.0) > 32.50
* (SkinThickness (41.0) > 32.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Glucose (137.0) > 122.50 AND Insulin (0.0) <= 189.00)
* (Glucose (137.0) > 122.50 AND BloodPressure (90.0) > 71.00)
* (Pregnancies (7.0) > 6.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Glucose (137.0) > 122.50 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (Glucose (137.0) > 122.50 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (Glucose (137.0) > 122.50 AND SkinThickness (41.0) > 32.50)
* (Glucose (137.0) > 122.50 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (Glucose (137.0) > 122.50 AND BMI (32.0) > 28.65)
* (Age (39.0) > 28.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Insulin (0.0) <= 189.00 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BMI (32.0) > 28.65 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Pregnancies (7.0) > 6.50 AND BloodPressure (90.0) > 71.00)
* (Pregnancies (7.0) > 6.50 AND Insulin (0.0) <= 189.00)
* (Pregnancies (7.0) > 6.50 AND BMI (32.0) > 28.65)
* (BloodPressure (90.0) > 71.00 AND DiabetesPedigreeFunction (0.39) <= 0.53) [[!] direction uncertain]
* (Age (39.0) > 28.50 AND Insulin (0.0) <= 189.00) [[!] direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.407

Factors impacting the probability for class Diabetic positively:
* (BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (BMI (30.0) > 28.65 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Insulin (0.0) <= 189.00 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (SkinThickness (0.0) <= 32.50 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Pregnancies (7.0) > 6.50 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* BMI (30.0) > 28.65
* (Glucose (100.0) <= 122.50 AND Insulin (0.0) <= 189.00)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (SkinThickness (0.0) <= 32.50 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50)
* Pregnancies (7.0) > 6.50
* (Glucose (100.0) <= 122.50 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* Age (32.0) > 28.50
* (BloodPressure (0.0) <= 71.00 AND BMI (30.0) > 28.65)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND BMI (30.0) > 28.65)
* (BMI (30.0) > 28.65 AND Age (32.0) > 28.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Age (32.0) > 28.50)
* SkinThickness (0.0) <= 32.50 [[!] direction uncertain]
* (BloodPressure (0.0) <= 71.00 AND Age (32.0) > 28.50)
* (Insulin (0.0) <= 189.00 AND BMI (30.0) > 28.65)
* (SkinThickness (0.0) <= 32.50 AND BMI (30.0) > 28.65) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Insulin (0.0) <= 189.00) [[!] direction uncertain]
* (BloodPressure (0.0) <= 71.00 AND Insulin (0.0) <= 189.00) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Pregnancies (7.0) > 6.50) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 122.50
* (Insulin (0.0) <= 189.00 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Pregnancies (7.0) > 6.50 AND Insulin (0.0) <= 189.00)
* (BloodPressure (0.0) <= 71.00 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Age (32.0) > 28.50 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* Insulin (0.0) <= 189.00
* (SkinThickness (0.0) <= 32.50 AND Insulin (0.0) <= 189.00)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Pregnancies (7.0) > 6.50 AND Age (32.0) > 28.50)
* (BMI (30.0) > 28.65 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (SkinThickness (0.0) <= 32.50 AND Age (32.0) > 28.50)
* (Insulin (0.0) <= 189.00 AND Age (32.0) > 28.50)
* (BloodPressure (0.0) <= 71.00 AND Pregnancies (7.0) > 6.50) [[!] direction uncertain]
* BloodPressure (0.0) <= 71.00 [[!] direction uncertain]
* (Pregnancies (7.0) > 6.50 AND BMI (30.0) > 28.65) [[!] direction uncertain]
* DiabetesPedigreeFunction (0.48) <= 0.53 [[!] direction uncertain]

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 122.50
* (Pregnancies (5.0) <= 6.50 AND BMI (25.8) <= 28.65)
* (Age (51.0) > 28.50 AND Pregnancies (5.0) <= 6.50)
* (Pregnancies (5.0) <= 6.50 AND SkinThickness (19.0) <= 32.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Pregnancies (5.0) <= 6.50)
* (Pregnancies (5.0) <= 6.50 AND Insulin (175.0) <= 189.00)
* (SkinThickness (19.0) <= 32.50 AND BMI (25.8) <= 28.65)
* Age (51.0) > 28.50
* (Age (51.0) > 28.50 AND BMI (25.8) <= 28.65)
* (Insulin (175.0) <= 189.00 AND BMI (25.8) <= 28.65)
* (Age (51.0) > 28.50 AND Insulin (175.0) <= 189.00)
* (Age (51.0) > 28.50 AND SkinThickness (19.0) <= 32.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND SkinThickness (19.0) <= 32.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND BMI (25.8) <= 28.65)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Insulin (175.0) <= 189.00) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* (Insulin (175.0) <= 189.00 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* (Pregnancies (5.0) <= 6.50 AND Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (BMI (25.8) <= 28.65 AND Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (Insulin (175.0) <= 189.00 AND DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* (Glucose (166.0) > 122.50 AND SkinThickness (19.0) <= 32.50)
* (SkinThickness (19.0) <= 32.50 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* BMI (25.8) <= 28.65
* (BMI (25.8) <= 28.65 AND DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (BMI (25.8) <= 28.65 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)

In [9]:
# 3. HTML - returns HTML table
html_narratives = explanations.to_narrative(
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="html",
)
from IPython.display import HTML

HTML(html_narratives)

In [10]:
# 4. Dictionary - returns list of dictionaries
dict_narratives = explanations.to_narrative(
    expertise_level="advanced", output_format="dict"
)
dict_narratives

[{'instance_index': 0,
  'factual_explanation_advanced': 'Prediction: Non-diabetic\nCalibrated Probability: 0.429\nPrediction Interval: [0.412, 0.441]\n\nFactors impacting the calibrated probability for class Diabetic positively:\nPregnancies (13.0) > 6.50                                                                            - weight ~ 0.267 [0.262, 0.295]\nGlucose (145.0) > 122.50                                                                             - weight ~ 0.152 [0.137, 0.193]\n(BMI (22.2) <= 28.65 AND DiabetesPedigreeFunction (0.24) <= 0.53)                                    - weight ~ 0.024 [0.009, 0.035]\nDiabetesPedigreeFunction (0.24) <= 0.53                                                              - weight ~ 0.007 [-0.008, 0.029] [[!] direction uncertain]\n\nFactors impacting the calibrated probability for class Diabetic negatively:\n(Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53) - weight ~ -0.319 [-0.367, -0.314]\n(Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)                                             - weight ~ -0.318 [-0.360, -0.312]\n(BMI (22.2) <= 28.65 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)                     - weight ~ -0.238 [-0.285, -0.226]\n(Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)                              - weight ~ -0.229 [-0.261, -0.220]\n(Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)                               - weight ~ -0.184 [-0.226, -0.169]\n(BMI (22.2) <= 28.65 AND Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)       - weight ~ -0.127 [-0.163, -0.111]\n(Glucose (145.0) > 122.50 AND BMI (22.2) <= 28.65)                                                   - weight ~ -0.104 [-0.139, -0.088]\n(BMI (22.2) <= 28.65 AND Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)      - weight ~ -0.098 [-0.126, -0.086]\n(Pregnancies (13.0) > 6.50 AND BMI (22.2) <= 28.65)                                                  - weight ~ -0.078 [-0.108, -0.065]\nBMI (22.2) <= 28.65                                                                                  - weight ~ -0.071 [-0.080, -0.061]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 1,
  'factual_explanation_advanced': 'Prediction: Non-diabetic\nCalibrated Probability: 0.499\nPrediction Interval: [0.490, 0.508]\n\nFactors impacting the calibrated probability for class Diabetic positively:\nBMI (34.1) > 28.65                                                                            - weight ~ 0.260 [0.250, 0.300]\n(BMI (34.1) > 28.65 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)                     - weight ~ 0.179 [0.152, 0.233]\n(Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)                                            - weight ~ 0.177 [0.154, 0.222]\n(Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)                                            - weight ~ 0.171 [0.147, 0.216]\n(Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 71.00)                                  - weight ~ 0.168 [0.141, 0.216]\n(BloodPressure (92.0) > 71.00 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)           - weight ~ 0.161 [0.134, 0.210]\n(BloodPressure (92.0) > 71.00 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)           - weight ~ 0.156 [0.129, 0.203]\nAge (38.0) > 28.50                                                                            - weight ~ 0.112 [0.080, 0.166]\n(SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)           - weight ~ 0.110 [0.081, 0.155]\n(SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)           - weight ~ 0.105 [0.079, 0.147]\n(Glucose (117.0) <= 122.50 AND SkinThickness (0.0) <= 32.50)                                  - weight ~ 0.098 [0.069, 0.143]\nSkinThickness (0.0) <= 32.50                                                                  - weight ~ 0.071 [0.058, 0.087]\n(SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 71.00) - weight ~ 0.069 [0.045, 0.103]\n\nFactors impacting the calibrated probability for class Diabetic negatively:\nGlucose (117.0) <= 122.50                                                                     - weight ~ -0.179 [-0.222, -0.158]\n(SkinThickness (0.0) <= 32.50 AND BMI (34.1) > 28.65)                                         - weight ~ -0.039 [-0.053, -0.028]\n(BloodPressure (92.0) > 71.00 AND SkinThickness (0.0) <= 32.50)                               - weight ~ -0.031 [-0.044, -0.021]\n(SkinThickness (0.0) <= 32.50 AND Age (38.0) > 28.50)                                         - weight ~ -0.028 [-0.044, -0.016]\n(BMI (34.1) > 28.65 AND Age (38.0) > 28.50)                                                   - weight ~ -0.018 [-0.038, 0.003] [[!] direction uncertain]\n(BloodPressure (92.0) > 71.00 AND Age (38.0) > 28.50)                                         - weight ~ -0.018 [-0.039, 0.002] [[!] direction uncertain]\nBloodPressure (92.0) > 71.00                                                                  - weight ~ -0.006 [-0.022, 0.009] [[!] direction uncertain]\n(BloodPressure (92.0) > 71.00 AND BMI (34.1) > 28.65)                                         - weight ~ -0.004 [-0.018, 0.010] [[!] direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 2,
  'factual_explanation_advanced': 'Prediction: Non-diabetic\nCalibrated Probability: 0.499\nPrediction Interval: [0.490, 0.508]\n\nFactors impacting the calibrated probability for class Diabetic positively:\nAge (60.0) > 28.50                                                                                      - weight ~ 0.338 [0.332, 0.366]\nBMI (36.0) > 28.65                                                                                      - weight ~ 0.294 [0.282, 0.339]\n(Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)                                                      - weight ~ 0.208 [0.185, 0.268]\n(BloodPressure (75.0) > 71.00 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)                     - weight ~ 0.207 [0.183, 0.268]\n(BMI (36.0) > 28.65 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)                               - weight ~ 0.189 [0.167, 0.236]\n(Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)                                            - weight ~ 0.184 [0.164, 0.223]\n(BMI (36.0) > 28.65 AND Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)                     - weight ~ 0.155 [0.127, 0.205]\n(Glucose (109.0) <= 122.50 AND BMI (36.0) > 28.65)                                                      - weight ~ 0.152 [0.125, 0.202]\nDiabetesPedigreeFunction (0.55) > 0.53                                                                  - weight ~ 0.078 [0.062, 0.100]\nBloodPressure (75.0) > 71.00                                                                            - weight ~ 0.071 [0.058, 0.087]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)           - weight ~ 0.051 [0.036, 0.073]\n(Glucose (109.0) <= 122.50 AND DiabetesPedigreeFunction (0.55) > 0.53)                                  - weight ~ 0.040 [0.016, 0.074]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00) - weight ~ 0.033 [0.012, 0.062]\n\nFactors impacting the calibrated probability for class Diabetic negatively:\nGlucose (109.0) <= 122.50                                                                               - weight ~ -0.188 [-0.223, -0.172]\n(BloodPressure (75.0) > 71.00 AND DiabetesPedigreeFunction (0.55) > 0.53)                               - weight ~ -0.098 [-0.140, -0.073]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Age (60.0) > 28.50)                                         - weight ~ -0.085 [-0.112, -0.068]\n(BMI (36.0) > 28.65 AND DiabetesPedigreeFunction (0.55) > 0.53)                                         - weight ~ -0.075 [-0.096, -0.061]\n(BloodPressure (75.0) > 71.00 AND Age (60.0) > 28.50)                                                   - weight ~ -0.066 [-0.107, -0.042]\n(BMI (36.0) > 28.65 AND Age (60.0) > 28.50)                                                             - weight ~ -0.028 [-0.044, -0.016]\n(BloodPressure (75.0) > 71.00 AND BMI (36.0) > 28.65)                                                   - weight ~ -0.016 [-0.027, -0.006]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 3,
  'factual_explanation_advanced': 'Prediction: Non-diabetic\nCalibrated Probability: 0.062\nPrediction Interval: [0.034, 0.064]\n\nFactors impacting the calibrated probability for class Diabetic positively:\n(Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)                     - weight ~ 0.432 [0.419, 0.444]\n(DiabetesPedigreeFunction (0.22) <= 0.53 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50) - weight ~ 0.405 [0.389, 0.418]\n(Pregnancies (3.0) <= 6.50 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)                     - weight ~ 0.397 [0.382, 0.410]\n(Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)                                             - weight ~ 0.396 [0.380, 0.408]\n(Pregnancies (3.0) <= 6.50 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)                 - weight ~ 0.387 [0.369, 0.401]\n(SkinThickness (24.0) <= 32.50 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)           - weight ~ 0.383 [0.366, 0.397]\n(BloodPressure (62.0) <= 71.00 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)           - weight ~ 0.359 [0.335, 0.374]\n(Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)                       - weight ~ 0.358 [0.335, 0.374]\n(Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)                                                   - weight ~ 0.357 [0.333, 0.374]\n(BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)                           - weight ~ 0.351 [0.317, 0.371]\n(DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)       - weight ~ 0.344 [0.312, 0.364]\n(SkinThickness (24.0) <= 32.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)                 - weight ~ 0.343 [0.316, 0.361]\n(BloodPressure (62.0) <= 71.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)                 - weight ~ 0.318 [0.274, 0.343]\n(BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)                                                   - weight ~ 0.289 [0.244, 0.311]\n(Insulin (0.0) <= 189.00 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)                       - weight ~ 0.289 [0.244, 0.311]\n(SkinThickness (24.0) <= 32.50 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)                 - weight ~ 0.286 [0.241, 0.309]\n(DiabetesPedigreeFunction (0.22) <= 0.53 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)       - weight ~ 0.280 [0.242, 0.299]\n(Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)                                               - weight ~ 0.280 [0.225, 0.309]\n(Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)                                         - weight ~ 0.272 [0.223, 0.297]\n(Pregnancies (3.0) <= 6.50 AND Age (25.0) <= 28.50)                                                   - weight ~ 0.267 [0.209, 0.296]\n(Glucose (108.0) <= 122.50 AND DiabetesPedigreeFunction (0.22) <= 0.53)                               - weight ~ 0.267 [0.209, 0.296]\n(SkinThickness (24.0) <= 32.50 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)             - weight ~ 0.266 [0.219, 0.289]\n(DiabetesPedigreeFunction (0.22) <= 0.53 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)   - weight ~ 0.264 [0.210, 0.292]\n(BMI (26.0) <= 28.65 AND Age (25.0) <= 28.50)                                                         - weight ~ 0.251 [0.216, 0.267]\n(SkinThickness (24.0) <= 32.50 AND Age (25.0) <= 28.50)                                               - weight ~ 0.246 [0.200, 0.269]\n(BloodPressure (62.0) <= 71.00 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)                 - weight ~ 0.227 [0.197, 0.240]\n(Insulin (0.0) <= 189.00 AND Age (25.0) <= 28.50)                                                     - weight ~ 0.205 [0.170, 0.218]\n(Pregnancies (3.0) <= 6.50 AND DiabetesPedigreeFunction (0.22) <= 0.53)                               - weight ~ 0.202 [0.142, 0.227]\n(BloodPressure (62.0) <= 71.00 AND Glucose (108.0) <= 122.50)                                         - weight ~ 0.198 [0.144, 0.221]\n(BMI (26.0) <= 28.65 AND Pregnancies (3.0) <= 6.50)                                                   - weight ~ 0.198 [0.160, 0.212]\n(BloodPressure (62.0) <= 71.00 AND Age (25.0) <= 28.50)                                               - weight ~ 0.197 [0.144, 0.219]\n(BloodPressure (62.0) <= 71.00 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)             - weight ~ 0.196 [0.145, 0.218]\n(DiabetesPedigreeFunction (0.22) <= 0.53 AND Age (25.0) <= 28.50)                                     - weight ~ 0.192 [0.143, 0.212]\n(Pregnancies (3.0) <= 6.50 AND SkinThickness (24.0) <= 32.50)                                         - weight ~ 0.156 [0.112, 0.168]\n(BloodPressure (62.0) <= 71.00 AND Pregnancies (3.0) <= 6.50)                                         - weight ~ 0.154 [0.110, 0.166]\n(Insulin (0.0) <= 189.00 AND Pregnancies (3.0) <= 6.50)                                               - weight ~ 0.126 [0.088, 0.135]\n(BloodPressure (62.0) <= 71.00 AND SkinThickness (24.0) <= 32.50)                                     - weight ~ 0.024 [-0.019, 0.028] [[!] direction uncertain]\n(BMI (26.0) <= 28.65 AND SkinThickness (24.0) <= 32.50)                                               - weight ~ 0.012 [-0.017, 0.014] [[!] direction uncertain]\n(BloodPressure (62.0) <= 71.00 AND DiabetesPedigreeFunction (0.22) <= 0.53)                           - weight ~ 0.006 [-0.028, 0.008] [[!] direction uncertain]\n(BMI (26.0) <= 28.65 AND DiabetesPedigreeFunction (0.22) <= 0.53)                                     - weight ~ 0.003 [-0.028, 0.005] [[!] direction uncertain]\n\nFactors impacting the calibrated probability for class Diabetic negatively:\nGlucose (108.0) <= 122.50                                                                             - weight ~ -0.282 [-0.311, -0.225]\nAge (25.0) <= 28.50                                                                                   - weight ~ -0.219 [-0.234, -0.186]\nPregnancies (3.0) <= 6.50                                                                             - weight ~ -0.155 [-0.168, -0.112]\nSkinThickness (24.0) <= 32.50                                                                         - weight ~ -0.027 [-0.031, 0.015] [[!] direction uncertain]\nDiabetesPedigreeFunction (0.22) <= 0.53                                                               - weight ~ -0.025 [-0.030, 0.021] [[!] direction uncertain]\nBMI (26.0) <= 28.65                                                                                   - weight ~ -0.024 [-0.028, 0.021] [[!] direction uncertain]\nBloodPressure (62.0) <= 71.00                                                                         - weight ~ -0.024 [-0.028, 0.021] [[!] direction uncertain]\nInsulin (0.0) <= 189.00                                                                               - weight ~ -0.003 [-0.005, 0.028] [[!] direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 4,

In [11]:
# Different expertise levels:

# Single level
beginner_only = explanations.to_narrative(
    expertise_level="beginner", output_format="text"
)
print(beginner_only)

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Pregnancies (13.0) > 6.50
* Glucose (145.0) > 122.50
* (BMI (22.2) <= 28.65 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* DiabetesPedigreeFunction (0.24) <= 0.53 [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (BMI (22.2) <= 28.65 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (BMI (22.2) <= 28.65 AND Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Glucose (145.0) > 122.50 AND BMI (22.2) <= 28.65)
* (BMI (22.2) <= 28.65 AND Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (Pregnancies (13.0) > 6.50 AND BMI (22.2) <= 28.65)
* BMI (22.2) <= 28.65

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 28.65
* (BMI (34.1) > 28.65 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* (Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)
* (Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* (Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 71.00)
* (BloodPressure (92.0) > 71.00 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)
* (BloodPressure (92.0) > 71.00 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* Age (38.0) > 28.50
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND Age (38.0) > 28.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 28.65)
* (Glucose (117.0) <= 122.50 AND SkinThickness (0.0) <= 32.50)
* SkinThickness (0.0) <= 32.50
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 71.00)

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* (SkinThickness (0.0) <= 32.50 AND BMI (34.1) > 28.65)
* (BloodPressure (92.0) > 71.00 AND SkinThickness (0.0) <= 32.50)
* (SkinThickness (0.0) <= 32.50 AND Age (38.0) > 28.50)
* (BMI (34.1) > 28.65 AND Age (38.0) > 28.50) [[!] direction uncertain]
* (BloodPressure (92.0) > 71.00 AND Age (38.0) > 28.50) [[!] direction uncertain]
* BloodPressure (92.0) > 71.00 [[!] direction uncertain]
* (BloodPressure (92.0) > 71.00 AND BMI (34.1) > 28.65) [[!] direction uncertain]

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.499

Factors impacting the probability for class Diabetic positively:
* Age (60.0) > 28.50
* BMI (36.0) > 28.65
* (Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (BloodPressure (75.0) > 71.00 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (BMI (36.0) > 28.65 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)
* (BMI (36.0) > 28.65 AND Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)
* (Glucose (109.0) <= 122.50 AND BMI (36.0) > 28.65)
* DiabetesPedigreeFunction (0.55) > 0.53
* BloodPressure (75.0) > 71.00
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 28.50)
* (Glucose (109.0) <= 122.50 AND DiabetesPedigreeFunction (0.55) > 0.53)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND BloodPressure (75.0) > 71.00)

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50
* (BloodPressure (75.0) > 71.00 AND DiabetesPedigreeFunction (0.55) > 0.53)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Age (60.0) > 28.50)
* (BMI (36.0) > 28.65 AND DiabetesPedigreeFunction (0.55) > 0.53)
* (BloodPressure (75.0) > 71.00 AND Age (60.0) > 28.50)
* (BMI (36.0) > 28.65 AND Age (60.0) > 28.50)
* (BloodPressure (75.0) > 71.00 AND BMI (36.0) > 28.65)

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (SkinThickness (24.0) <= 32.50 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (BloodPressure (62.0) <= 71.00 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (SkinThickness (24.0) <= 32.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (BloodPressure (62.0) <= 71.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 28.50)
* (BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (SkinThickness (24.0) <= 32.50 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (Pregnancies (3.0) <= 6.50 AND Age (25.0) <= 28.50)
* (Glucose (108.0) <= 122.50 AND DiabetesPedigreeFunction (0.22) <= 0.53)
* (SkinThickness (24.0) <= 32.50 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 28.65 AND Age (25.0) <= 28.50)
* (SkinThickness (24.0) <= 32.50 AND Age (25.0) <= 28.50)
* (BloodPressure (62.0) <= 71.00 AND BMI (26.0) <= 28.65 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Age (25.0) <= 28.50)
* (Pregnancies (3.0) <= 6.50 AND DiabetesPedigreeFunction (0.22) <= 0.53)
* (BloodPressure (62.0) <= 71.00 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 28.65 AND Pregnancies (3.0) <= 6.50)
* (BloodPressure (62.0) <= 71.00 AND Age (25.0) <= 28.50)
* (BloodPressure (62.0) <= 71.00 AND Insulin (0.0) <= 189.00 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Age (25.0) <= 28.50)
* (Pregnancies (3.0) <= 6.50 AND SkinThickness (24.0) <= 32.50)
* (BloodPressure (62.0) <= 71.00 AND Pregnancies (3.0) <= 6.50)
* (Insulin (0.0) <= 189.00 AND Pregnancies (3.0) <= 6.50)
* (BloodPressure (62.0) <= 71.00 AND SkinThickness (24.0) <= 32.50) [[!] direction uncertain]
* (BMI (26.0) <= 28.65 AND SkinThickness (24.0) <= 32.50) [[!] direction uncertain]
* (BloodPressure (62.0) <= 71.00 AND DiabetesPedigreeFunction (0.22) <= 0.53) [[!] direction uncertain]
* (BMI (26.0) <= 28.65 AND DiabetesPedigreeFunction (0.22) <= 0.53) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (108.0) <= 122.50
* Age (25.0) <= 28.50
* Pregnancies (3.0) <= 6.50
* SkinThickness (24.0) <= 32.50 [[!] direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.53 [[!] direction uncertain]
* BMI (26.0) <= 28.65 [[!] direction uncertain]
* BloodPressure (62.0) <= 71.00 [[!] direction uncertain]
* Insulin (0.0) <= 189.00 [[!] direction uncertain]

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.518

Factors impacting the probability for class Diabetic positively:
* (BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (BloodPressure (90.0) > 71.00 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (BMI (32.0) > 28.65 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (Pregnancies (7.0) > 6.50 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (Insulin (0.0) <= 189.00 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (Insulin (0.0) <= 189.00 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (BloodPressure (90.0) > 71.00 AND BMI (32.0) > 28.65)
* (Pregnancies (7.0) > 6.50 AND SkinThickness (41.0) > 32.50)
* (Insulin (0.0) <= 189.00 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* BMI (32.0) > 28.65
* (Pregnancies (7.0) > 6.50 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (Pregnancies (7.0) > 6.50 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (SkinThickness (41.0) > 32.50 AND Insulin (0.0) <= 189.00)
* (Age (39.0) > 28.50 AND BloodPressure (90.0) > 71.00)
* (BloodPressure (90.0) > 71.00 AND Insulin (0.0) <= 189.00)
* Glucose (137.0) > 122.50
* (DiabetesPedigreeFunction (0.39) <= 0.53 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (Insulin (0.0) <= 189.00 AND BMI (32.0) > 28.65) [[!] direction uncertain]
* Age (39.0) > 28.50
* Pregnancies (7.0) > 6.50
* (Age (39.0) > 28.50 AND BMI (32.0) > 28.65) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.39) <= 0.53 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.39) <= 0.53 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50) [[!] direction uncertain]
* (SkinThickness (41.0) > 32.50 AND DiabetesPedigreeFunction (0.39) <= 0.53) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* DiabetesPedigreeFunction (0.39) <= 0.53
* (Pregnancies (7.0) > 6.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Insulin (0.0) <= 189.00 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BloodPressure (90.0) > 71.00 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BMI (32.0) > 28.65 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Age (39.0) > 28.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* Insulin (0.0) <= 189.00
* BloodPressure (90.0) > 71.00
* SkinThickness (41.0) > 32.50
* (SkinThickness (41.0) > 32.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Glucose (137.0) > 122.50 AND Insulin (0.0) <= 189.00)
* (Glucose (137.0) > 122.50 AND BloodPressure (90.0) > 71.00)
* (Pregnancies (7.0) > 6.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Glucose (137.0) > 122.50 AND Age (39.0) > 28.50 AND SkinThickness (41.0) > 32.50)
* (Glucose (137.0) > 122.50 AND BloodPressure (90.0) > 71.00 AND SkinThickness (41.0) > 32.50)
* (Glucose (137.0) > 122.50 AND SkinThickness (41.0) > 32.50)
* (Glucose (137.0) > 122.50 AND SkinThickness (41.0) > 32.50 AND BMI (32.0) > 28.65)
* (Glucose (137.0) > 122.50 AND BMI (32.0) > 28.65)
* (Age (39.0) > 28.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Insulin (0.0) <= 189.00 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BMI (32.0) > 28.65 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Pregnancies (7.0) > 6.50 AND BloodPressure (90.0) > 71.00)
* (Pregnancies (7.0) > 6.50 AND Insulin (0.0) <= 189.00)
* (Pregnancies (7.0) > 6.50 AND BMI (32.0) > 28.65)
* (BloodPressure (90.0) > 71.00 AND DiabetesPedigreeFunction (0.39) <= 0.53) [[!] direction uncertain]
* (Age (39.0) > 28.50 AND Insulin (0.0) <= 189.00) [[!] direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.407

Factors impacting the probability for class Diabetic positively:
* (BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (BMI (30.0) > 28.65 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Insulin (0.0) <= 189.00 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (SkinThickness (0.0) <= 32.50 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (Insulin (0.0) <= 189.00 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Pregnancies (7.0) > 6.50 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* BMI (30.0) > 28.65
* (Glucose (100.0) <= 122.50 AND Insulin (0.0) <= 189.00)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 28.65)
* (SkinThickness (0.0) <= 32.50 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND BloodPressure (0.0) <= 71.00 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50)
* Pregnancies (7.0) > 6.50
* (Glucose (100.0) <= 122.50 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50 AND Age (32.0) > 28.50)
* Age (32.0) > 28.50
* (BloodPressure (0.0) <= 71.00 AND BMI (30.0) > 28.65)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND BMI (30.0) > 28.65)
* (BMI (30.0) > 28.65 AND Age (32.0) > 28.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Age (32.0) > 28.50)
* SkinThickness (0.0) <= 32.50 [[!] direction uncertain]
* (BloodPressure (0.0) <= 71.00 AND Age (32.0) > 28.50)
* (Insulin (0.0) <= 189.00 AND BMI (30.0) > 28.65)
* (SkinThickness (0.0) <= 32.50 AND BMI (30.0) > 28.65) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Insulin (0.0) <= 189.00) [[!] direction uncertain]
* (BloodPressure (0.0) <= 71.00 AND Insulin (0.0) <= 189.00) [[!] direction uncertain]
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Pregnancies (7.0) > 6.50) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 122.50
* (Insulin (0.0) <= 189.00 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Pregnancies (7.0) > 6.50 AND Insulin (0.0) <= 189.00)
* (BloodPressure (0.0) <= 71.00 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Age (32.0) > 28.50 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* Insulin (0.0) <= 189.00
* (SkinThickness (0.0) <= 32.50 AND Insulin (0.0) <= 189.00)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (Pregnancies (7.0) > 6.50 AND Age (32.0) > 28.50)
* (BMI (30.0) > 28.65 AND SkinThickness (0.0) <= 32.50 AND Pregnancies (7.0) > 6.50)
* (SkinThickness (0.0) <= 32.50 AND Age (32.0) > 28.50)
* (Insulin (0.0) <= 189.00 AND Age (32.0) > 28.50)
* (BloodPressure (0.0) <= 71.00 AND Pregnancies (7.0) > 6.50) [[!] direction uncertain]
* BloodPressure (0.0) <= 71.00 [[!] direction uncertain]
* (Pregnancies (7.0) > 6.50 AND BMI (30.0) > 28.65) [[!] direction uncertain]
* DiabetesPedigreeFunction (0.48) <= 0.53 [[!] direction uncertain]

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Non-diabetic
Calibrated Probability: 0.429

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 122.50
* (Pregnancies (5.0) <= 6.50 AND BMI (25.8) <= 28.65)
* (Age (51.0) > 28.50 AND Pregnancies (5.0) <= 6.50)
* (Pregnancies (5.0) <= 6.50 AND SkinThickness (19.0) <= 32.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Pregnancies (5.0) <= 6.50)
* (Pregnancies (5.0) <= 6.50 AND Insulin (175.0) <= 189.00)
* (SkinThickness (19.0) <= 32.50 AND BMI (25.8) <= 28.65)
* Age (51.0) > 28.50
* (Age (51.0) > 28.50 AND BMI (25.8) <= 28.65)
* (Insulin (175.0) <= 189.00 AND BMI (25.8) <= 28.65)
* (Age (51.0) > 28.50 AND Insulin (175.0) <= 189.00)
* (Age (51.0) > 28.50 AND SkinThickness (19.0) <= 32.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND SkinThickness (19.0) <= 32.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND BMI (25.8) <= 28.65)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Insulin (175.0) <= 189.00) [[!] direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* (Insulin (175.0) <= 189.00 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* (Pregnancies (5.0) <= 6.50 AND Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (BMI (25.8) <= 28.65 AND Glucose (166.0) > 122.50 AND Insulin (175.0) <= 189.00)
* (Insulin (175.0) <= 189.00 AND DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* (Glucose (166.0) > 122.50 AND SkinThickness (19.0) <= 32.50)
* (SkinThickness (19.0) <= 32.50 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)
* BMI (25.8) <= 28.65
* (BMI (25.8) <= 28.65 AND DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50)
* (BMI (25.8) <= 28.65 AND Age (51.0) > 28.50 AND Glucose (166.0) > 122.50)

In [12]:
# Multiple levels
all_levels = explanations.to_narrative(
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="dataframe",
)
all_levels

,instance_index,factual_explanation_beginner,factual_explanation_intermediate,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, intermediate, advanced)",binary_classification
1,1,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, intermediate, advanced)",binary_classification
2,2,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, intermediate, advanced)",binary_classification
3,3,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, intermediate, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
5,5,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, intermediate, advanced)",binary_classification
6,6,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, intermediate, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
9,9,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, intermediate, advanced)",binary_classification

In [13]:
# Template path handling:

# If exp.yaml doesn't exist, automatically falls back to explain_template.yaml
narratives = explanations.to_narrative(
    template_path="exp.yaml",  # Will use default if not found
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)
narratives

C:\Users\loftuw\Documents\Github\moffran\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1626: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, advanced)",binary_classification
1,1,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, advanced)",binary_classification
2,2,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, advanced)",binary_classification
3,3,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
5,5,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, advanced)",binary_classification
6,6,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
9,9,Prediction: Non-diabetic\nCalibrated Probabili...,Prediction: Non-diabetic\nCalibrated Probabili...,"(beginner, advanced)",binary_classification

In [14]:
# Use custom template
narratives = explanations.to_narrative(
    template_path="/path/to/custom_template.yaml",
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)

# Use default template
narratives = explanations.to_narrative(
    expertise_level=("beginner", "advanced"), output_format="dataframe"
)

print("The to_narrative method provides a clean, intuitive API for generating narratives!")

C:\Users\loftuw\Documents\Github\moffran\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1626: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

The to_narrative method provides a clean, intuitive API for generating narratives!